stages:
- name: Build
  steps:
  - runScriptConfig:
      image: busybox
      shellScript: eval $(aws ecr get-login --region eu-west-1 | sed 's/-e none//')
  - runScriptConfig:
      image: docker:git
      shellScript: |- 
        docker build 319701921293.dkr.ecr.eu-west-1.amazonaws.com/nginx:${CICD_EXECUTION_SEQUENCE} .
        docker push 319701921293.dkr.ecr.eu-west-1.amazonaws.com/nginx:${CICD_EXECUTION_SEQUENCE}
#  when:
#    branch:
#      include:
#      - master
#    event:
#      include:
#      - push
#      - pull_request
timeout: 60
notification: {}
