stages:
- name: Build
  when:
      branch: master
      event: [ push, pull_request ]
  steps:
  - runScriptConfig:
      image: busybox
      shellScript: docker build 319701921293.dkr.ecr.eu-west-1.amazonaws.com/nginx:${CICD_EXECUTION_SEQUENCE} .
  - runScriptConfig:
      image: busy
      shellScript: eval $(aws ecr get-login --region eu-west-1 | sed 's/-e none//')
  - runScriptConfig:
      image: busy
      shellScript: docker push 319701921293.dkr.ecr.eu-west-1.amazonaws.com/nginx:${CICD_EXECUTION_SEQUENCE}
timeout: 60
notification: {}
